@url = http://127.0.0.1:3000
@id = 3
@data_inicial = data_inicial=2020-01-01
@data_final = data_final=2020-01-31
//Gets
GET {{url}}/turmas HTTP/1.1
Accept: application/json
###
GET {{url}}/turmas?{{data_inicial}}&{{data_final}} HTTP/1.1
###
GET {{url}}/turmas/{{id}} HTTP/1.1
Accept: application/json
###
//Posts
POST {{url}}/turmas HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "nome": "capataz",
    "ativo": false,
    "email": "capataz@gmail",
    "role": "segurança"
}
###
//Puts
PUT {{url}}/turmas/{{id}} HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "desc_nivel": "intermediario"
}
###
//Deletes
DELETE {{url}}/turmas/{{id}} HTTP/1.1
Accept: application/json